Vagrant.configure("2") do |config|
  config.vm.box = "centos7-custom"

  config.vbguest.auto_update = false
  config.vm.box_check_update = false
  config.vm.synced_folder ".", "/vagrant", disabled: true

  # Config une première VM "node1"
  config.vm.define "node1" do |node1|
    # remarquez l'utilisation de 'node1.' défini sur la ligne au dessus
    node1.vm.network "private_network", ip: "192.168.2.11"
  
    node1.vm.provider "virtualbox" do |v|
      v.memory = 1024
      v.name = "node1.tp2.b2"
    end
  end

  # Config une première VM "node2"
  config.vm.define "node2" do |node2|
    # remarquez l'utilisation de 'node2.' défini sur la ligne au dessus
    node2.vm.network "private_network", ip: "192.168.2.12"

    node2.vm.provider "virtualbox" do |v|
      v.memory = 512
      v.name = "node2.tp2.b2"
    end
  end
end